import { Inter } from "next/font/google";
import "./globals.css";
import { Box, Toolbar } from "@mui/material";
import Header from "../../src/app/Header";
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Faisal Masud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Box>
          <Header />
          <Toolbar />
        </Box>
        {children}
      </body>
    </html>
  );
}
